name: random-walk-microstructures
channels:
  - conda-forge
dependencies:
  - conda-forge::pip=21.2.4
  - conda-forge::python=3.9.12
  - pip:
    - autopep8==2.3.1
    - matplotlib==3.9.2
    - numpy==1.26.4
    - pylint==3.3.1
    - scikit-learn==1.5.2
    - torch==2.2.2
    - scikit-image==0.24.0
    - triangle==20230923
